import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[font]
size = 16
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }

[window]
# decorations = "none"

[window.padding]
x = 7
y = 7

[env]
term = "xterm-256color"
